version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-shareit-image
    container_name: gateway-shareit-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server-shareit-image
    container_name: server-shareit-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qwerty

  db:
    image: postgres:14-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=admin
      - POSTGRES_DB=shareit