spring:
  profiles:
    active:
      dev
---
spring:
  config:
    activate:
      on-profile:
        dev

server:
  port: 8080

shareit-server:
  url: ${SHAREIT_SERVER_URL}

logging:
  level:
    org.springframework.web.client.RestTemplate:
      DEBUG