spring:
  profiles:
    active:
      prod
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090
---
spring:
  config:
    activate:
      on-profile:
        - default
        - dev
        - test
        - ci

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: test
    password: test

logging:
  level:
    org.springframework:
      orm.jpa:
        - INFO
        - JpaTransactionManager: DEBUG
      transaction:
        - INFO
        - interceptor: TRACE

---

spring:
  config:
    activate:
      on-profile:
        - prod

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}




